version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/usna-acebook
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: scripts/Beforeinstall.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/reload-pm2.sh
      timeout: 300
      runas: root